version: '3.1'
services:
  postgres:
    image: 'postgres:latest'
    hostname: 'postgres'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgvol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamadminiamadminiamadmin
      - POSTGRES_DB=athlete_view
  mongo:
    image: 'mongo:7.0'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongovol:/data/
      - $PWD/db_init/mongo/:/docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongousr
      - MONGO_INITDB_ROOT_PASSWORD=1mongo3mongo3mongo7
      - MONGO_INITDB_DATABASE=athlete_view
  rabbitmq:
    image: 'rabbitmq:management-alpine'
    hostname: 'rabbit'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=guest"
      - "RABBITMQ_DEFAULT_PASS=guest"
volumes:
  pgvol:
  mongovol:
networks:
  default:
    name: athlete_view