logging:
  level:
    root: INFO
    ase: TRACE


spring:
  data:
    mongodb:
        host: 127.0.0.1
        database: athlete_view
        port: 27017
        username: mongousr
        password: 1mongo3mongo3mongo7
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/athlete_view
    username: postgres
    password: iamadminiamadminiamadmin
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: mail.gmx.net
    username: athlete.view@gmx.at
    password: fjsdokfasojksfaojlsafjlkfsa
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.2

security:
  jwt:
    token:
      secret-key: very-very-secret-key-oh-yes-you-can-trust-me-i-know-hehe

app:
  scheduling:
    enable: true