spring:
  data:
    mongodb:
      host: localhost
      database: athlete_view
      port: 27017
      username: mongo
      password: 1mongo3mongo3mongo7
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/athlete_view
    username: postgres
    password: iamadminiamadminiamadmin
  jpa:
    hibernate:
      ddl-auto: create

security:
  jwt:
    token:
      secret-key: very-very-secret-key-oh-yes-you-can-trust-me-i-know-hehe
