version: '3.1'
services:  
  rabbitmq:
    image: 'rabbitmq:management-alpine'
    hostname: 'rabbit'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=guest"
      - "RABBITMQ_DEFAULT_PASS=guest"
volumes:
  pgvol:
  mongovol:
networks:
  default:
    name: athlete_view
